version: 0.0
os: linux
files:
  - source: goapp
    destination: /home/ubuntu/goapp/
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 60
      runas: ubuntu
 