version: 0.0
os: linux
files:
  - source: goapp
    destination: /home/ubuntu/goapp/
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
