name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  applicationfolder: goapp
  AWS_REGION: us-east-1
  S3BUCKET: code_deploy


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18' # The Go version to download (if necessary) and use.
      
    # Install all the dependencies
    # - name: Install dependencies
    #   run: |
    #     go version
    #     go get -u golang.org/x/lint/golint
        
    # Run build of the application
    - name: Run build
      id: package
      working-directory: ${{ env.applicationfolder }}   
      run: go build . 
      
    - name: chmod
      run: chmod -R +x ./.github



      # - name: Upload Artifact to s3
      #   working-directory: ${{ env.applicationfolder }}/
      #   run: aws s3 cp * s3://${{ env.S3BUCKET }}/
        
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: Dev
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
  #       role-session-name: GitHub-Action-Role
  #       aws-region: ${{ env.AWS_REGION }}
  #   - run: |
  #       echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
  #       commit_hash=`git rev-parse HEAD`
  #       aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures