name: Build and Deploy

on:
  push:
    branches: [ gh-actions-codedeploy ]

env:
  applicationfolder: goapp

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          
      - name: Run build
        id: package
        working-directory: ${{ env.applicationfolder }}   
        run: go build







