name: Build and Deploy

on:
  push:
    branches: [ master ]

env:
  applicationfolder: goapp
  AWS_REGION: us-east-1
  S3BUCKET: code-deploy-bucket-saba

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    myapp:
        appname: ['goapp']
        deploy-group: ['goapp']
        s3-bucket: ['code-deploy-bucket-saba']
        s3-filename: ['goapp-${{ github.sha }}']

    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}  
  
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          
      - name: Run build
        id: package
        working-directory: ${{ env.applicationfolder }}   
        run: go build
        

      -  name: Install AWS CLI v2
         run:  |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      - name: AWS Deploy push
        run: |
          aws deploy push \
          --application-name ${{ myapp.appname }} \
          --description "This is a revision for the ${{ myapp.appname }}-${{ github.sha }}" \
          --ignore-hidden-files \
          --s3-location s3://${{ myapp.s3-bucket }}/${{ myapp.s3-filename }}.zip \
          --source . 